### ISSUE TITLE
If the version is not listed in `.ocamlformat`, lint-fmt will fail.

### ISSUE THREAD

**Issue by HikaruEgashira** [ocaml/setup-ocaml#388]
If the version is not listed in `.ocamlformat`, lint-fmt will fail.
This is due to the fact that if version is not specified, version will be `undefined`.

https://github.com/HikaruEgashira/sat-solver/runs/4797615555?check_suite_focus=true#step:7:14

**Comment by smorimoto** [comment]
That is documented. In general, the ocamlformat team currently recommends that always include the version field and the base preset field. I think there is a document about them somewhere, but I can explain them if you couldn't find. Anyway, the problem here can be thought of as an error not being issued properly. Would you like to tackle with it?

**Comment by HikaruEgashira** [comment]
I understand. Now we'll print the appropriate error if the version doesn't exist.
