### ISSUE TITLE
slow and doesn't work for me

### ISSUE THREAD

**Issue by mimoo** [ocaml/setup-ocaml#551]
Sorry to bump a thread, but I tried using this today and it was quite slow compared to a simple `apt install ocaml` (which takes ~40s on average). Is this normal?

It also looks like it doesn't have the same effect, as ocaml-rs doesn't work anymore (https://github.com/zshipko/ocaml-rs) if I install it with your github action

**Comment by smorimoto** [comment]
There are technically some differences between installing OCaml using the system package manager and setting up an environment called the opam switch using opam. I think there was a comprehensive explanation somewhere, can you point to that? @dra27

**Comment by dra27** [comment]
Separating the two parts: installing OCaml from the OS package manager (`apt`, `brew`, etc.) will always be faster because they're precompiled binaries. However, with virtually every OS package manager you then have no control over the version of OCaml you get. opam, on the other hand, can use your OS's distribution of OCaml (via the `ocaml-system` package) but otherwise builds the compiler from sources. In setup-ocaml (and other CI systems), that gets mitigated by using caches (which is effectively what Ubuntu's repositories are). There are various other approaches built on top of opam (e.g. opam-bin and esy) which add binary caching, but opam is fundamentally a source-based package manager.

For the second part, "doesn't work for me" is not exactly the most precise bug report! 🙂 From a cursory look at the repo, it's not clear to me whether you have this working locally with an opam-based workflow? Assuming that's right, I'd suggest starting there before moving on to getting it into CI - Docker is useful for experimenting with this, for example:

```Dockerfile
FROM ocaml/opam:ubuntu-22.04-ocaml-4.14
RUN sudo ln -f /usr/bin/opam-2.1 /usr/bin/opam && opam update
```

gives you an Ubuntu LTS starting point with opam 2.1 and a switch with OCaml 4.14 already compiled but with relatively few other dependencies installed.
