### ISSUE TITLE
Suggest a reasonable `jobs.<job_id>.concurrency` for the OCaml project

### ISSUE THREAD

**Issue by smorimoto** [ocaml/setup-ocaml#666]
Using `jobs.<job_id>.concurrency` may be a good way to avoid overwhelming an organisation or project's parallelism. In general, OCaml projects still tend to run longer per workflow, and this action pretty much solves that, but it would be nice to get better at using resources with features like this.
The official documentation is here, but I'm trying to figure out what kind of setup to recommend. Any ideas?
https://docs.github.com/en/actions/using-jobs/using-concurrency
For instance, PR should have no problem canceling workflows other than the most recent commit. But how about on the mainline? Should we show which commit failed on the way? And so on, I have a lot of doubts.

**Comment by smorimoto** [comment]
@dra27 I believe you probably have an idea that makes a lot of sense!

**Comment by dra27** [comment]
The compiler started using it a while back (ocaml/ocaml#11730). We do cancel for branches as well as PRs, but in practice it happens quite rarely for trunk, looking at the logs.

My only reservation is that really it's about good use of GItHub Actions rather than setup-ocaml itself. I guess it could be encouraged by putting it in the sample workflow in the README (i.e. having a demo which would cancel running PR workflows on a fresh push, for example)?
