### ISSUE TITLE
Install depexts before creating the switch

### ISSUE THREAD

**Issue by Gbury** [ocaml/setup-ocaml#68]
When using the `v2` of the action, and an ocaml-version (or rather a list of base packages for a switch) that targets 32bits executables (e.g. `4.11.2+32bit`, or `ocaml-variants.4.12.0+options,ocaml-option-32bit`), the build of the compiler fails (see https://github.com/Gbury/dolmen/pull/62/checks?check_run_id=2235477332 ).

From what I can tell, this is because in such a case, we need to install `gcc-mutlilib` (which is correctly listed as a depext of `ocaml-option-32bit`) **before** creating the switch, since the compilation of the compiler (and thus the creation of the switch) requires it. That means that in the list of steps mentioned [here](https://github.com/avsm/setup-ocaml/pull/66#issue-601660144), there would be a need to run opam depext before creating the switch (in addition to the current process where it is run last), which I presume would mean requiring opam `>= 2.1` with depext builtin, since before creating the switch we won't be able to install depext via opam.

**Comment by smorimoto** [comment]
Thank you for testing this! Since musl stuff is installed by default whether we need it or not, I think we can add some necessary libraries as well, so I'll do it.

**Comment by smorimoto** [comment]
@Gbury This has been fixed in the latest v2 branch!

**Comment by Gbury** [comment]
That's great ! Thanks a lot for the quick fix, :)

From looking at the fix, it seems that the v2 now unconditionally installs the mutlilib packages required, which is fine and reasonable, but it seems a bit too specific a fix maybe ? In the sense that if/when another configuration option for ocaml requires a depext (potentially less reasonable to install unconditionally than some multilib packages), the action will need to be fixed, whereas the necessary info will be in the configuration option's opam package depext, which should probably be used instead of hardcoding things ?
More generally, if any package in the `ocaml-version` list (which if I understand correctly, actually is more the list of packages that forms the base of the switch rather than simply an ocaml version) actually need a depext that is not hardcoded and unconditionally installed by the action, then the setup will fail. How hard would it be to support that general case ?

**Comment by smorimoto** [comment]
Your point is really correct! I would like to fix in a reasonable way after 2.1 rather than the quick fix.

**Comment by smorimoto** [comment]
> More generally, if any package in the ocaml-version list (which if I understand correctly, actually is more the list of packages that forms the base of the switch rather than simply an ocaml version) actually need a depext that is not hardcoded and unconditionally installed by the action, then the setup will fail. How hard would it be to support that general case ?

I still don't understand what kind of case this is referring to. Can you explain in more detail?

**Comment by smorimoto** [comment]
Oh, I misunderstood it a little (actually **quite**)! I thought you were talking about another [ocaml-version](https://github.com/ocurrent/ocaml-version) :sweat_smile: 

Yeah, definitely. For example, it's easy to implement a simple (and fragile) guard that triggers an error if the comma-separated package name does not contain the word "ocaml". It's obvious that this is not an essential fix at all, but I think it's impossible (or difficult) to essentially solve this at the moment without making some changes to opam itself.

Since all compiler packages have compiler flags in their package files, it should actually be very easy to print errors from opam based on them. In other words, we just need to expose something like `--compiler` flag apart from `--packages` flag.

https://github.com/ocaml/opam-repository/blob/3ab68de6a7f70472960c004c2fc7301d442ddcfc/packages/ocaml-base-compiler/ocaml-base-compiler.4.12.0/opam#L16
