### ISSUE TITLE
Expose opam installation path to outputs

### ISSUE THREAD

**Issue by cometkim** [ocaml/setup-ocaml#818]
Currently the action doesn't specify any output, but it would be nice to add some to interact with other actions.

For example, providing the installation path by tool-cache as output would make it easier for other actions to access the cached `opam` command.

also installed version, arch, etc.

**Comment by cometkim** [comment]
The actual use case was here https://github.com/rescript-lang/rescript-compiler/pull/6842

`opam env` didn't work well (especially on windows), so I had to copy envs from the `setup-ocaml` action. IMO, exposing some details can maximize the composability between actions without copying its details.

It is a common and useful practice of `setup-*` actions (e.g. [setup-python](https://github.com/actions/setup-python/blob/main/action.yml)) to provide information about the installed tool path, the exact version installed, whether there was a cache hit, etc.

**Comment by smorimoto** [comment]
Caching about OCaml/opam on the user side requires quite a bit of real-world knowledge, and even then it can only be said that it's very unstable, and is entirely outside the scope of support for the action. The decisions about when to save and restore the cache, the cache keys, and many other things are based on really complex criteria that are almost impossible to do by the user, which is why the action exists. It's virtually impossible to get any faster than just using the action as-is.

**Comment by smorimoto** [comment]
Even if it does appear to work at the moment, it will surely break somewhere or the build won't be reproducible. That's the same as not working.
