### ISSUE TITLE
Store opam path in a env variable?

### ISSUE THREAD

**Issue by davesnx** [ocaml/setup-ocaml#898]
I want to cache the entire opam switch and also the opam binary, which the only form I found is to run a script to capture it:

```
- name: Get OPAM executable path
  if: steps.opam-cache.outputs.cache-hit != 'true'
  uses: actions/github-script@v7
  with:
    script: |
      const opamPath = await io.which('opam', true);
      console.log('opam executable found: %s', opamPath);

      const fs = require('fs/promises');
      await fs.writeFile('.opam-path', opamPath, 'utf-8');
      console.log('stored path to .opam-path');
```

Took it from @cknitt's work on rescript. Probably he's interested as well

Would be possible to store this into a github variable?

**Comment by cknitt** [comment]
> Took it from @cknitt's work on rescript. Probably he's interested as well

Actually @cometkim's work. 🙂 

But definitely interested, too.

**Comment by cometkim** [comment]
See https://github.com/ocaml/setup-ocaml/issues/818

**Comment by smorimoto** [comment]
I really don't recommend caching the entire switch.

**Comment by davesnx** [comment]
Yes, I read it on the other issue.

This comment https://github.com/ocaml/setup-ocaml/issues/818#issuecomment-2201007354 caught me by surprise. Since I have a different experience with caching "the entire world," for example, in ahrefs, we share the switch and also the build folder on each run and haven't faced "out of sync" issues, but it's a more closed environment where opam repo is also embedded.

Anyway, I would like to know what "real world knowledge" I might lack in order to do it myself and also what the complexity is around `hen to save and restore the cache, the cache keys, and many other things are based on really complex criteria that are almost impossible to do by the user.`.

**Comment by cometkim** [comment]
> I really don't recommend caching the entire switch.

Cache is problematic, I can understand the consideration.

But if I really face a big problem, I can own the risk of customization.

ReScript used to wait 18 minutes for every commit of PR, but after introducing cache, we only wait 6 minutes. We have been using it for 5 months already. Saved A LOT of time.

One thing we experience that the risk we actually take is very small. We have very small dependencies and we rarely update them. The cache got currupted once recently, but we were able to recover it immediately by just clearing the cache entry in the GitHub UI.

Even if it breaks right now and we have to spend a few days maintaining it again, it is already well worth it in terms of the time saving in iterations everyday.

So, I'd say that it was actually worth it to us at least. But I'm not talking about upstreaming it, and I'm not trying to hand off the responsibility of its side effects

I'm just asking expose a little context value so user who willing to build composite actions can find escape hatch. I don't believe it's that difficult to maintain.

**Comment by smorimoto** [comment]
I think there are some negative effects of the current incremental package version selection mechanism in the opam ecosystem. If you're building an app rather than a package, this won't be much of a problem in the closed world, but if you're building a package, the build may actually be broken, but you may be far behind in noticing it.

I believe that people should notice that, as early as possible, and I think that is the main responsibility of CI. Anyway, I think the mechanism which can lead to the illusion that something is broken is not broken is quite dangerous.

Honestly, I don't think there's much advantage to using this action if you're taking a risk. In fact, opam's own repository does not use this action. They understand the trade-offs and make that choice.
